url: https://dfmcmurray.github.io/
baseurl: /diabetes-calendar/

# Site settings
title: 2015 Calendar
email: dfmcmurray@gmail.com
description: "Diabetes Calendar :: All proceeds will go to charity."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6899D3
  secondary: 4284D3   
  secondary-dark: 333

# Team names, titles and social links
people:
- pic: 9
- pic: 1
- pic: 6
- pic: 4
- pic: 7
- pic: 8
- pic: 5
- pic: 3
- pic: 2

# Team members per row
peoplePerRow: 4

# More Info links
links:

- url: "http://donate.jdrf.org/info/jdrf-qa/#about"
  icon: jdrf.jpeg
  desc: "JDRF's mission is to find a cure for type 1 diabetes (T1D) and its complications through the support of research."

- url: "http://diatribe.org"
  icon: diaTribe.jpg
  desc: "Research and product news for people with diabetes."

- url: "http://carbdm.org"
  icon: carbdm.jpg
  desc: "Helping people with T1D seize diabetes and lead healthier, happier lives by connecting with a strong T1D community."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty