url: https://dfmcmurray.github.io/
baseurl: ""

# Site settings
title: T1D Exposed
brand: T1D Exposed
email: dfmcmurray@gmail.com
description: "Diabetes Calendar :: All proceeds will go to charity."
calendarPrice: 20

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6899D3
  secondary: 4284D3   
  secondary-dark: 333

# Team names, titles and social links
people:
- pic: 9
- pic: 1
- pic: 6
- pic: 4
- pic: 7
- pic: 8
- pic: 5
- pic: 3
- pic: 2

# Team members per row
peoplePerRow: 4

# More Info links
links:

- url: "http://donate.jdrf.org/info/jdrf-qa/#about"
  icon: jdrf.jpeg
  desc: "JDRF's mission is to find a cure for type 1 diabetes (T1D) and its complications through the support of research."

- url: "http://diatribe.org"
  icon: diaTribe.jpg
  desc: "Research and product news for people with diabetes."

- url: "http://carbdm.org"
  icon: carbdm.jpg
  desc: "Helping people with T1D seize diabetes and lead healthier, happier lives by connecting with a strong T1D community."

#Sponsors
sponsors:

- url: "http://facebook.com"
  icon: facebook.jpg

- url: "http://taralayman.com"
  icon: tara-layman-photography-dark.png

- url: "http://dfmwebstudio.com"
  icon: "dfm-web-studio.png"

# Build settings
markdown: kramdown
permalink: pretty