url: https://dfmcmurray.github.io/
baseurl: ""

# Site settings
title: T1D Exposed
brand: T1D Exposed
email: dfmcmurray@gmail.com
description: "Diabetes Calendar :: All proceeds will go to charity."
calendarPrice: 20

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6899D3
  secondary: 4284D3   
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Rick
  occupation: Retired Hairstylist and JDRF Board Member
  yearsWithDiabetesText: Living with T1D for 10 years.
- name: Jenny
  occupation: Roller Derby Enthusiast
  yearsWithDiabetesText: Living with T1D for 33 years.
- name: Rob
  occupation: Scientist
  yearsWithDiabetesText: Living with T1D for 6 years.
- name: Leigh
  occupation: Journalist
  yearsWithDiabetesText: Living with T1D for 20 years.
- name: Callie
  occupation: Ultimate Clemson Tigers Football Enthusiast
  yearsWithDiabetesText: Living with T1D for 30 years.
- name: Anthony
  occupation: Health Coach 
  yearsWithDiabetesText: Living with T1D for 11 years.
- name: Lauren
  occupation: Professional Skier
  yearsWithDiabetesText: Living with T1D since childhood
- name: Ryan
  occupation: Gardener 
  yearsWithDiabetesText: Living with T1D for 37 years.
- name: John
  occupation: Lumberjack
  yearsWithDiabetesText: Living with T1D for 18 years.
- name: Kim
  occupation: Social Justice Activist 
  yearsWithDiabetesText: Living with T1D for 22 years.
- name: Nick
  occupation: Video Gamer
  yearsWithDiabetesText: Living with T1D for 8 years.
- name: Kelly
  occupation: New Mom and Yogi
  yearsWithDiabetesText: Living with T1D for 23 years.
- name: Doris
  occupation: Entrepreneur & Luxury Model
  yearsWithDiabetesText: Living with T1D for 4 years.
- name: Anna
  occupation: Nurse
  yearsWithDiabetesText: Living with T1D for 27 years.

# Team members per row
peopleInFirstRow: 4
peoplePerRow: 5

# More Info links
links:

- url: "http://carbdm.org"
  icon: carbdm.jpg
  desc: "Helping people with T1D seize diabetes and lead healthier, happier lives by connecting with a strong T1D community."

- url: "http://donate.jdrf.org/info/jdrf-qa/#about"
  icon: jdrf.jpeg
  desc: "JDRF's mission is to find a cure for type 1 diabetes (T1D) and its complications through the support of research."

- url: "http://dyf.org/"
  icon: dyf.png
  desc: "DYF’s education and recreational programs equip children, teens & families with the courage, competence and confidence to live well with T1D."

#Sponsors
sponsors:

- url: "http://taralayman.com"
  icon: tara-layman-logo.jpg

- url: "http://dfmwebstudio.com"
  icon: "dfm-web-studio.png"

- url: "http://www.rebelsun.com/"
  icon: "rebelsun.png"

# Build settings
markdown: kramdown
permalink: pretty