url: https://dfmcmurray.github.io/
baseurl: ""

# Site settings
title: T1D Exposed
brand: T1D Exposed
email: dfmcmurray@gmail.com
description: "Diabetes Calendar :: All proceeds will go to charity."
calendarPrice: 20

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6899D3
  secondary: 4284D3   
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Rick
  occupation: Retired Hairstylist and JDRF Board Member
  yearsWithDiabetes: 10
- name: Jenny
  occupation: Roller Derby Enthusiast
  yearsWithDiabetes: 33
- name: Robert
  occupation: Scientist
  yearsWithDiabetes: 8
- name: Leigh
  occupation: Journalist
  yearsWithDiabetes: 20
- name: Callie
  occupation: Ultimate Clemson Tigers Football Enthusiast
  yearsWithDiabetes: 30
- name: Anthony
  occupation: Health Coach 
  yearsWithDiabetes: 11
- name: Lauren
  occupation: Professional Skier
  yearsWithDiabetes: 20
- name: Ryan
  occupation: Gardener 
  yearsWithDiabetes: 37
- name: John
  occupation: Lumberjack
  yearsWithDiabetes: 18
- name: Kim
  occupation: Social Justice Activist 
  yearsWithDiabetes: 22
- name: Nick
  occupation: Video Gamer
  yearsWithDiabetes: 8
- name: Kelly
  occupation: New Mom and Yogi
  yearsWithDiabetes: 23
- name: Doris
  occupation: Entrepreneur & Luxury Model
  yearsWithDiabetes: 4
- name: Anna
  occupation: Nurse
  yearsWithDiabetes: 27

# Team members per row
peopleInFirstRow: 4
peoplePerRow: 4

# More Info links
links:

- url: "http://carbdm.org"
  icon: carbdm.jpg
  desc: "Helping people with T1D seize diabetes and lead healthier, happier lives by connecting with a strong T1D community."

- url: "http://donate.jdrf.org/info/jdrf-qa/#about"
  icon: jdrf.jpeg
  desc: "JDRF's mission is to find a cure for type 1 diabetes (T1D) and its complications through the support of research."

- url: "http://dyf.org/"
  icon: dyf.png
  desc: "DYF’s education and recreational programs equip children, teens & families with the courage, competence and confidence to live well with T1D."

#Sponsors
sponsors:

- url: "http://taralayman.com"
  icon: tara-layman-logo.jpg

- url: "http://dfmwebstudio.com"
  icon: "dfm-web-studio.png"

- url: "http://www.rebelsun.com/"
  icon: "rebelsun.png"

# Build settings
markdown: kramdown
permalink: pretty