url: https://dfmcmurray.github.io/
baseurl: ""

# Site settings
title: T1D Exposed
brand: T1D Exposed
email: dfmcmurray@gmail.com
description: "Diabetes Calendar :: All proceeds will go to charity."
calendarPrice: 20

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6899D3
  secondary: 4284D3   
  secondary-dark: 333

# Team names, titles and social links
people:
- pic: 9
  name: Tara
  occupation: Photographer
  yearsWithDiabetes: 20
- pic: 1
  name: Lucas
  occupation: Founder of DASH Camp
  yearsWithDiabetes: 19
- pic: 6
  name: Kat
  occupation: Healthcare Professional
  yearsWithDiabetes: 15
- pic: 4
  name: Courtney
  occupation: Community Builder
  yearsWithDiabetes: 13
- pic: 7
  name: Omid
  occupation: Researcher at Facebook
  yearsWithDiabetes: 9
- pic: 8
  name: Julia
  occupation: Hospitality and Tourism Student
  yearsWithDiabetes: 19
- pic: 5
  name: Johanna
  occupation: Nursing Student
  yearsWithDiabetes: 7
- pic: 3
  name: Claire
  occupation: Fashion and Consumer Studies Student
  yearsWithDiabetes: 18
- pic: 2
  name: Sam
  occupation: Clinical Social Worker
  yearsWithDiabetes: 1
- pic: 10
  name: Jeannie
  occupation: "RN, CDE, Camp Nurse"
  yearsWithDiabetes: 50
- pic: 11
  name: Stephanie
  occupation: Graduate Student in Cinema Studies
  yearsWithDiabetes: 10
- pic: 12
  name: Emily
  occupation: Legal Studies Student
  yearsWithDiabetes: 12
- pic: 13
  name: Marit
  occupation: Executive Assistant/Student
  yearsWithDiabetes: 21
# Team members per row
peopleInFirstRow: 4
peoplePerRow: 3

# More Info links
links:

- url: "http://carbdm.org"
  icon: carbdm.jpg
  desc: "Helping people with T1D seize diabetes and lead healthier, happier lives by connecting with a strong T1D community."

- url: "http://donate.jdrf.org/info/jdrf-qa/#about"
  icon: jdrf.jpeg
  desc: "JDRF's mission is to find a cure for type 1 diabetes (T1D) and its complications through the support of research."

- url: "http://dyf.org/"
  icon: dyf.png
  desc: "DYF’s education and recreational programs equip children, teens & families with the courage, competence and confidence to live well with T1D."

#Sponsors
sponsors:

- url: "http://taralayman.com"
  icon: tara-layman-logo.jpg

- url: "http://dfmwebstudio.com"
  icon: "dfm-web-studio.png"

- url: "http://iheartguts.com/"
  icon: "iheartguts.png"

# Build settings
markdown: kramdown
permalink: pretty