url: https://dfmcmurray.github.io/
baseurl: ""

# Site settings
title: T1D Exposed
brand: T1D Exposed
email: dfmcmurray@gmail.com
description: "Diabetes Calendar :: All proceeds will go to charity."
calendarPrice: 20

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6899D3
  secondary: 4284D3   
  secondary-dark: 333

# Team names, titles and social links
people:
- name: 1
  occupation: Actress and Action Star
  yearsWithDiabetes: 18
- name: 2
  occupation: Personal Trainer and Health Coach
  yearsWithDiabetes: 14
- name: 3
  occupation: Entrepreneur
  yearsWithDiabetes: 50
- name: 4
  occupation: Founder of Type One Diabetic Sugar Mommas
  yearsWithDiabetes: 30
- name: 5
  occupation: Philosophy Student
  yearsWithDiabetes: 2
- name: 6
  occupation: Healthcare Professional 
  yearsWithDiabetes: 62
- name: 7
  occupation: Entrepreneur
  yearsWithDiabetes: 5
- name: 8
  occupation: Biologist and Potter 
  yearsWithDiabetes: 22
- name: 9
  occupation: "Executive Producer: TV, Sports, Music"
  yearsWithDiabetes: 3
- name: 10
  occupation: Type One Diabetes Clinical Trial Coordinator 
  yearsWithDiabetes: 20
- name: 11
  occupation: Mechanical Engineer
  yearsWithDiabetes: 24
- name: 12
  occupation: Writer and Content Developer
  yearsWithDiabetes: 22
- name: 13
  occupation: Writer and Content Developer
  yearsWithDiabetes: 22
- name: 14
  occupation: Writer and Content Developer
  yearsWithDiabetes: 22

# Team members per row
peopleInFirstRow: 4
peoplePerRow: 4

# More Info links
links:

- url: "http://carbdm.org"
  icon: carbdm.jpg
  desc: "Helping people with T1D seize diabetes and lead healthier, happier lives by connecting with a strong T1D community."

- url: "http://donate.jdrf.org/info/jdrf-qa/#about"
  icon: jdrf.jpeg
  desc: "JDRF's mission is to find a cure for type 1 diabetes (T1D) and its complications through the support of research."

- url: "http://dyf.org/"
  icon: dyf.png
  desc: "DYF’s education and recreational programs equip children, teens & families with the courage, competence and confidence to live well with T1D."

#Sponsors
sponsors:

- url: "http://taralayman.com"
  icon: tara-layman-logo.jpg

- url: "http://dfmwebstudio.com"
  icon: "dfm-web-studio.png"

- url: "http://www.rebelsun.com/"
  icon: "rebelsun.png"

# Build settings
markdown: kramdown
permalink: pretty